nim doc -o:docs/NimCord.html src/nimcord.nim
nim doc -o:docs/Cache.html src/nimcord/cache.nim
nim doc -o:docs/Channel.html src/nimcord/channel.nim
nim doc -o:docs/Client.html src/nimcord/client.nim
nim doc -o:docs/ClientObjects.html src/nimcord/clientobjects.nim
nim doc -o:docs/DiscordObject.html src/nimcord/discordobject.nim
nim doc -o:docs/Embed.html src/nimcord/embed.nim
nim doc -o:docs/Emoji.html src/nimcord/emoji.nim
nim doc -o:docs/EventDispatcher.html src/nimcord/eventdispatcher.nim
nim doc -o:docs/EventHandler.html src/nimcord/eventhandler.nim
nim doc -o:docs/Guild.html src/nimcord/guild.nim
nim doc -o:docs/Image.html src/nimcord/image.nim
nim doc -o:docs/Member.html src/nimcord/member.nim
nim doc -o:docs/Message.html src/nimcord/message.nim
nim doc -o:docs/Nimcordutils.html src/nimcord/nimcordutils.nim
nim doc -o:docs/Permission.html src/nimcord/permission.nim
nim doc -o:docs/Presence.html src/nimcord/presence.nim
nim doc -o:docs/Role.html src/nimcord/role.nim
nim doc -o:docs/User.html src/nimcord/user.nim
nim doc -o:docs/User.html src/nimcord/commandsystem.nim